version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: docker/images/app/Dockerfile
    depends_on:
      - db
    environment:
      - ENVIRONMENT=DEV
      - NODE_ENV=production
      - PGHOST=db
      - PGUSER=postgres
      - DATABASE_URL=${DATABASE_URL}

 
  db:
    image: postgres:12.1